### ISSUE TITLE
Warning in ioBroker log file

### ISSUE THREAD

**Issue by derjj2018** [iobroker-community-adapters/ioBroker.discovergy#131]
The LogFile of ioBroker shows every minute a Warning.

discovergy.0 | 2020-10-11 15:24:02.992 | warn | (19089) This value will not be set in future versions. Please report this to the developer.
-- | -- | -- | --
discovergy.0 | 2020-10-11 15:24:02.991 | warn | (19089) State value to set is invalid for discovergy.0.61228767.info.location: The state contains the forbidden properties street, streetNumber, zip, city, country!

![image](https://user-images.githubusercontent.com/44620765/95679810-9030f800-0bd5-11eb-94f8-973c29da1af8.png)

**Versions:**  
 - Adapter version: 0.5.0
 - JS-Controller version: 3.1.6
 - Node version: v10.22.1
 - Operating system: Ubuntu 18.04.5 LTS

**Comment by DutchmanNL** [comment]
Fixed in latest version
