### ISSUE TITLE
registration is not recognized

### ISSUE THREAD

**Issue by Siegmunder** [iobroker-community-adapters/ioBroker.discovergy#138]
My registration is not recognized. The demo mode works.  What am I doing wrong. 
Many thanks for your help. 
Regards Uwe
[Log.pdf](https://github.com/iobroker-community-adapters/ioBroker.discovergy/files/5421342/Log.pdf)

**Comment by DutchmanNL** [comment]
Sorry, misser this one is the error stil present ?
