### ISSUE TITLE
Problem with discovergy adapter since js-controller 3.2.16

### ISSUE THREAD

**Issue by weggetor** [iobroker-community-adapters/ioBroker.discovergy#182]
**Describe the bug**  
I updated iobroker js-controller to Version 3.2.16 and now the adapter is not working any more (stays in "red" state)

**Expected behavior**  
Should be starting normal

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/5718742/108607452-dc304c80-73c0-11eb-92ec-6606f8734a2b.png)

**Versions:**  
 - Adapter version: 0.5.0
 - JS-Controller version: 3.2.16
 - Node version: <node-version> 
 - Operating system: Ubuntu 19 in ProxMox VM

**Main error:**
Error: The state contains the forbidden properties street, streetNumber, zip, city, country!

**Comment by PhagoZ** [comment]
I have the same problem on my site.
just updated today and got the same issue.

**Comment by man10to** [comment]
I have the same problem on my site.
just updated today and got the same issue.
!


Platform
    linux
Betriebssystem
    linux
Architektur
    x64
CPUs
    6
Geschwindigkeit
    1799 MHz
Modell
    Intel(R) Xeon(R) CPU E5-2630L v3 @ 1.80GHz
RAM
    4.7 GB
System Betriebszeit
    00:29:52
Node.js
    v14.16.0 (Empfohlene Version v12.21.0)
NPM
    6.14.11
Festplatte Größe
    195.86 GB
Festplatte frei
    186.42 GB
Anzahl der Adapter
    329
Betriebszeit
    00:11:20
Aktive Instanzen
    25
Hostname
    iobroker



_```
discovergy.0 | 2021-02-24 13:31:12.395 | error | (5914) The state contains the forbidden properties street, streetNumber, zip, city, country!
-- | -- | -- | --
discovergy.0 | 2021-02-24 13:31:12.395 | error | (5914) Error: The state contains the forbidden properties street, streetNumber, zip, city, country!     at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter
discovergy.0 | 2021-02-24 13:31:12.394 | error | (5914) unhandled promise rejection: The state contains the forbidden properties street, streetNumber, zip, city, country!
discovergy.0 | 2021-02-24 13:31:12.394 | error | (5914)  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
discovergy.0 | 2021-02-24 13:31:12.393 | error | (5914) The state contains the forbidden properties street, streetNumber, zip, city, country!
discovergy.0 | 2021-02-24 13:31:12.392 | error | (5914) Error: The state contains the forbidden properties street, streetNumber, zip, city, country!     at validateSetStateObjectArgument (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter
discovergy.0 | 2021-02-24 13:31:12.390 | error | (5914) unhandled promise rejection: The state contains the forbidden properties street, streetNumber, zip, city, country!
discovergy.0 | 2021-02-24 13:31:12.390 | error | (5914)  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by rejecting a  promise which was not handled with .catch().
```_

**Comment by philoxio** [comment]
Same here! Anyone manged to solve this one?

**Comment by DutchmanNL** [comment]
> Same here! Anyone manged to solve this one?

wil check today, needed to find time with al other projects and priority sorry :/

**Comment by DutchmanNL** [comment]
Seems this is already fixed long time ago in version 0.5.4, will release that to stable... meanwhile you can update to 0.5.4 by beta repo
