### ISSUE TITLE
Voltage unknown

### ISSUE THREAD

**Issue by PhagoZ** [iobroker-community-adapters/ioBroker.discovergy#196]
![issue_discovergy](https://user-images.githubusercontent.com/53466094/111346052-233af600-867e-11eb-8d23-53371a1d5df2.JPG)

is there a solution for this?

raspberrypi
Platform   linux
Betriebssystem   linux
Architektur   arm
CPUs   4
Geschwindigkeit    1500 MHz
Modell   ARMv7 Processor rev 3 (v7l)
RAM    1.82 GB
System Betriebszeit  00:26:39
Node.js   v12.21.0
NPM  6.14.11
Festplatte Größe    58.27 GB
Festplatte frei    54.65 GB
Anzahl der Adapter    333
Betriebszeit   00:26:35
Aktive Instanzen   15

**Comment by DutchmanNL** [comment]
> is there a solution for this?

jup, version 0.5.5 :) https://github.com/iobroker-community-adapters/ioBroker.discovergy/commit/4266cd7acfe2566af7071426af71cb6c150b9d0b
