### ISSUE TITLE
Unknown Voltage another time - still in v0.5.5

### ISSUE THREAD

**Issue by PhagoZ** [iobroker-community-adapters/ioBroker.discovergy#197]
had this problem befor, but developer, closed it to fast.

the issue is still there
![adapter_issue_version](https://user-images.githubusercontent.com/53466094/111488905-f77d4600-8739-11eb-8ea4-eaece9976993.JPG)
![adapter_issue_log](https://user-images.githubusercontent.com/53466094/111488916-fa783680-8739-11eb-88d1-5a25f24908c2.JPG)

**Comment by DutchmanNL** [comment]
sorry my fault, I implemented voltage and power instead of Voltage and Power.
0.5.6 released : https://github.com/iobroker-community-adapters/ioBroker.discovergy/commit/08d704a07d7cd691ab607d962daba734bdf61acb
