### ISSUE TITLE
kWh für den aktuellen Monat

### ISSUE THREAD

**Issue by ghost** [iobroker-community-adapters/ioBroker.discovergy#20]
Hi,

der Adapter zeigt mir derweil alle wichtigen Daten an. 
Was mir persönlich fehlt ist die Anzeige der kWh nur für den aktuellen Monat.
So kann man einfacher seine Kostenberechnung starten.

Gruß

**Comment by DutchmanNL** [comment]
hi @AI3x,

Die API gibt leider diese werte nicht weiter soweit mir bekannt ist dadurch kann der discovergy diese auch nicht darstellen.

Genau für diese Funktionalität (verbrauch darstellen pro tag, Woche, Monat, Quartal usw.) habe ich einen andere Adapter entwickelt : https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix

dieser kann sowohl Daten aus discovergy als jeden anderen Adapter/geraet was einen kWh gerammt wert darstellt die nötigen Berechnungen erledigen.

Mein Empfehlung währe dann auch diesen ein zu setzen.

Greetz,

Dutch

**Comment by AI3x** [comment]
Doch, das ist ohne Probleme über den Endpoint statistics möglich.
Dann braucht man für Discovergy auf jedenfall keinen weiteren Adapter!
Ich teste gerade in einem fork wie man das am besten umsetzen kann.

**Comment by AI3x** [comment]
Es würde gehen über den Endpoint "statistic" indem man den Parameter "from" auf den Ersten des aktuellen Monats setzt.

**Comment by DutchmanNL** [comment]
> Es würde gehen über den Endpoint "statistic" indem man den Parameter "from" auf den Ersten des aktuellen Monats setzt.

ich verstehe dich gerade nicht

**Comment by AI3x** [comment]
Ok, ich versuche mal ein wenig Licht ins Dunkel zu bringen.
Du nutzt momentan den Endpoint "last_readings" aus der Api. Discovergy stellt aber auch noch weitere Endpoints zur Verfügung um Daten abzugreifen. Ich habe das im Fork schon mal getestet. funktioniert super...

**Comment by DutchmanNL** [comment]
Alles klar jetzt verstehe ich danke!

Dan muss ich mir die endpoints Mal anschauen und Ausbauen oder hast du das bereits Dan adopte ich es.

Muß halt nur aufpassen mit der Session das die API nicht zuviel request bekommt und Blickes die Basis habe ich aber bereits verarbeitet

**Comment by DutchmanNL** [comment]
> Du nutzt momentan den Endpoint "last_readings" aus der Api. Discovergy stellt aber auch noch weitere Endpoints zur Verfügung um Daten abzugreifen.

habe mir deinen code mal angeschaut ist doch ganz OK, die set states kann ich weiter in Funktionen abfangen damit der code bissl kleiner und effizienter wird.

Die frage wird jetzt eher lauten welche endpoints allgemein alle nötig sind, meine Idee :

- Alle wichtigen endpoints einlesen nicht nur die last_reading
- Werte auslesen (mit jetziger function) zum erstellen und updaten der states

Ich könnte noch Hilfe gebrauchen welche endpoints von der API relevant sind um Daten zu ermitteln (ich war der Meinung last_reading hatte alles nötige)

Könntest du mir bitte helfen in de research welche endpoints interessant sind ?
Ich kan dan den code mal komplett dazu umbauen (müssen auch noch par andere kleine Sachen effizienter gebaut werden) und dan haben wir nen komplett Übersicht der Daten.

Ich würde dan auch die Beträge nicht hard-coded in der source hinterlegen (wen ich deine fork richtig interpretiert habe wird das da gemacht) sonder als eingebafeld im admin.
(noch schoener waehre wen auch die kosten aus der API geliefert werden würden)

Cheers,

Dutch

**Comment by AI3x** [comment]
Ja das wäre ne gute Idee...
Ich habe das bei mir nur auf die schnelle mal eben zum testen umgebaut.
Der Basispreis und die kWh gibt die API leider nicht zurück, da wäre also die Config schon ideal.
Ich schau mir das wenn ich Zeit hab nochmals an.

**Comment by DutchmanNL** [comment]
Danke!
Ich habe leider momentan ein bisschen wenig Zeit um die Research zu machen aber wen wir da zusammenkommen können gerne das wird schon

**Comment by DutchmanNL** [comment]
user account und damit die daten und links leider gelöscht :/
