### ISSUE TITLE
Send this information to developer : xxxxx

### ISSUE THREAD

**Issue by Whistler67** [iobroker-community-adapters/ioBroker.discovergy#40]
Hi
ich habe seit gestern (31.08.19) den Fehler
Information received from Discovergy which is not yet part of this adapter"
			"Send this information to developer : xxxxx
im log.
Kannst Du das prüfen ?

Danke
Whistler67
[logs - ioBroker.zip](https://github.com/iobroker-community-adapters/ioBroker.discovergy/files/3563121/logs.-.ioBroker.zip)

**Comment by Andy200877** [comment]
Bei mir das gleiche.....



discovergy.0 | 2019-09-01 14:05:46.879 | error | Send this information to developer : loadProfileType : SLP
-- | -- | -- | --
discovergy.0 | 2019-09-01 14:05:46.879 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-01 14:05:46.879 | error | Send this information to developer : fullSerialNumber : 1ESY1161228098
discovergy.0 | 2019-09-01 14:05:46.879 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-01 14:05:46.879 | error | Send this information to developer : manufacturerId : ESY
discovergy.0 | 2019-09-01 14:05:46.878 | error | Information received from Discovergy which is not yet part of this adapter

**Comment by DutchmanNL** [comment]
cool, neue Funktionen ich mal mich mal dran :)

**Comment by danielhainich** [comment]
2019-09-02 07:39:47.783  - debug: discovergy.0 ready - Adapter: databases are connected and adapter received configuration
2019-09-02 07:39:47.786  - debug: discovergy.0 client_secret decrypt ready
2019-09-02 07:39:47.933  - error: discovergy.0 Information received from Discovergy which is not yet part of this adapter
2019-09-02 07:39:47.933  - error: discovergy.0 Send this information to developer : manufacturerId : EMH
2019-09-02 07:39:47.933  - error: discovergy.0 Information received from Discovergy which is not yet part of this adapter
2019-09-02 07:39:47.933  - error: discovergy.0 Send this information to developer : fullSerialNumber : 1EMH0123456789
2019-09-02 07:39:47.933  - error: discovergy.0 Information received from Discovergy which is not yet part of this adapter
2019-09-02 07:39:47.933  - error: discovergy.0 Send this information to developer : loadProfileType : RLM

**Comment by detafun** [comment]
Geht wohl weiter:

  |   |   |  
-- | -- | -- | --
discovergy.0 | 2019-09-08 09:44:29.478 | error | Send this information to developer : loadProfileType : SLP
discovergy.0 | 2019-09-08 09:44:29.478 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-08 09:44:29.477 | error | Send this information to developer : fullSerialNumber : 1ESY1xxxxxxx

**Comment by DutchmanNL** [comment]
Hoffentlich diese Woche Zeit das alles zu debuggen scheinbar kommen fast jede Woche Sachen dazu

**Comment by detafun** [comment]
Wäre cool

**Comment by detafun** [comment]
Wenn du schon dabei bist. Kannst du vielleicht von awattar noch diese Grafig einbinden.
$ curl https://api.awattar.de/v1/marketdata

Liefert die Strompreisdaten von Jetzt bis zu 24 Stunden in die Zukunft.

Wäre weltklasse, das als json drinnen zu haben.

**Comment by Ridesa** [comment]
discovergy.0 | 2019-09-11 13:08:09.511 | error | Send this information to developer : loadProfileType : SLP
-- | -- | -- | --
discovergy.0 | 2019-09-11 13:08:09.511 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-11 13:08:09.511 | error | Send this information to developer : fullSerialNumber : 1ESY1160866992
discovergy.0 | 2019-09-11 13:08:09.511 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-11 13:08:09.511 | error | Send this information to developer : manufacturerId : ESY

häng mich mal dran :)

**Comment by danielhainich** [comment]
hallo, wie ist der Stand bezüglich der Integration der neuen Adapter?

**Comment by CKMartens** [comment]
Als ad-hoc Maßnahme habe ich bei mir nach Zeile 180 die folgenden drei hinzugefügt:
case "loadProfileType":
case "fullSerialNumber":
case "manufacturerId":

Damit wirft er wenigstens erst einmal keine Fehler mehr und liefert Daten. 

Da

**Comment by detafun** [comment]
> Als ad-hoc Maßnahme habe ich bei mir nach Zeile 180 die folgenden drei hinzugefügt:
> case "loadProfileType":
> case "fullSerialNumber":
> case "manufacturerId":
> 
> Damit wirft er wenigstens erst einmal keine Fehler mehr und liefert Daten.
> 
> Da

Wo in welcher Datei?

Ich hoffe aber das DutchmanNL das bald hinbekommt.

**Comment by Flocki76** [comment]
Hänge mich hier auch mal mit dran.
LG

discovergy.0 | 2019-09-22 11:47:05.566 | error | Information received from Discovergy which is not yet part of this adapter
-- | -- | -- | --
discovergy.0 | 2019-09-22 11:46:45.620 | error | Send this information to developer : loadProfileType : SLP
discovergy.0 | 2019-09-22 11:46:45.620 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-22 11:46:45.620 | error | Send this information to developer : fullSerialNumber :
discovergy.0 | 2019-09-22 11:46:45.620 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-22 11:46:45.620 | error | Send this information to developer : manufacturerId : ESY
discovergy.0 | 2019-09-22 11:46:45.619 | error | Information received from Discovergy which is not yet part of this adapter

**Comment by detafun** [comment]
Wir müssen warten. Und hoffen, das  DutchmanNL Zeit hat das kurz einzupflegen.
Vielleicht kann er ja mal ein kurzes Zwischen Feedback geben,

**Comment by CKMartens** [comment]
> Wo in welcher Datei?
Im Verzeichniss /opt/iobroker/node_modules/iobroker.discovergy liegt die Datei main.js Dort nach der Zeile 180 die drei vor der Zeile mit
 break;
einfügen.

**Comment by Gilias-Ger** [comment]
Habe die gleichen Fehlermeldungen...

Quelle | Zeit | debug | Meldung
-- | -- | -- | --
discovergy.0 | 2019-09-23 23:38:26.533 | error | Send this information to developer : loadProfileType : SLP
discovergy.0 | 2019-09-23 23:38:26.532 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-23 23:38:26.532 | error | Send this information to developer : fullSerialNumber : 1ESY1161229817
discovergy.0 | 2019-09-23 23:38:26.532 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-23 23:38:26.532 | error | Send this information to developer : manufacturerId : ESY
discovergy.0 | 2019-09-23 23:38:26.531 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-23 23:37:56.527 | error | Send this information to developer : loadProfileType : SLP
discovergy.0 | 2019-09-23 23:37:56.527 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-23 23:37:56.527 | error | Send this information to developer : fullSerialNumber : 1ESY1161229817
discovergy.0 | 2019-09-23 23:37:56.527 | error | Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-09-23 23:37:56.527 | error | Send this information to developer : manufacturerId : ESY
discovergy.0 | 2019-09-23 23:37:56.526 | error | Information received from Discovergy which is not yet part of this adapter

**Comment by detafun** [comment]
> > Wo in welcher Datei?
> > Im Verzeichniss /opt/iobroker/node_modules/iobroker.discovergy liegt die Datei main.js Dort nach der Zeile 180 die drei vor der Zeile mit
> > break;
> > einfügen.

hat erst mal funktioniert.

**Comment by Gilias-Ger** [comment]
Das sind die Fehlermeldungen im Log von ioB, ja der Adapter hat mal funktioniert.

Wo soll ich was eintragen?

                                                case "serialNumber":
                                                case "type":
                                                case "voltageScalingFactor":
                                                        break;

                                                default:

                                                        adapter.log.error("Information received from Discovergy which is not yet part of this adapter");
                                                        adapter.log.error("Send this information to developer : " + x + " : " + meterobjects[x]);

**Comment by CKMartens** [comment]
> hat erst mal funktioniert.
Vieleicht macht Dutchman das blad fix. Schön das ich erstmal helfen konnte

**Comment by philoxio** [comment]
> > > Wo in welcher Datei?
> > > Im Verzeichniss /opt/iobroker/node_modules/iobroker.discovergy liegt die Datei main.js Dort nach der Zeile 180 die drei vor der Zeile mit
> > > break;
> > > einfügen.
> 
> hat erst mal funktioniert.

bei mir auch, danke!

**Comment by Andy200877** [comment]
Ich habe bei Zeile 180 weit und breit kein "break;"

Meine Zeile 180 sieht so aus : 

`
           // expected, that detect method will add to _instances one instance of specif
            adapters[a].detect(device._addr, device, options, (err, isFound, addr) => {
                if (callbacks[adpr]) {
==> ZEILE 180:          adapter.log.error('Double callback by "' + adpr + '"');
                } else {
                    callbacks[adpr] = true;
                }

                if (isFound) {
                    adapter.log.debug('Test ' + device._addr + ' ' + adpr + ' DETECTED!')
                }
                if (timeout) {
 ` 


Vielleicht könnte mir jemand etwas genauer sagen wo es hin muss. Mit ein paar Zeilen org. Code.

Ich hoffe DutchmanNL pflegt es bald richtig ein....

**Comment by CKMartens** [comment]
> Ich habe bei Zeile 180 weit und breit kein "break;"

@Andy200877 Du bist in einer ganz falschen Datei. Schau Dir hier im Repo unter Code mal die msin.js an.

**Comment by DutchmanNL** [comment]
alpha of new version release, beta will be available soon for everyone https://github.com/iobroker-community-adapters/ioBroker.discovergy/commit/3b6aaf01c39b520a9470a99b3de60f30069bf9df
