### ISSUE TITLE
Momentanwert jetziger Abgabe stimmt nicht

### ISSUE THREAD

**Issue by philoxio** [iobroker-community-adapters/ioBroker.discovergy#50]
Hi!

![image](https://user-images.githubusercontent.com/50422054/66714866-a8044f00-edbc-11e9-8a83-9ebdad231db1.png)

Hier scheint in der aktuellen Version etwas verrutscht zu sein.

Der Wert "Momentanwert jetzige Abgabe" stimmt nicht (sieht aus als sei es der Abnahmewert * 1000),

**Comment by DutchmanNL** [comment]
danke mir garnicht aufgefallen, bitte die version 0.4.8 probieren sollte damit gelöst sein.
Und abgäbe werte jetzt ohne - .....

**Comment by DutchmanNL** [comment]
fixed 0.4.8
