### ISSUE TITLE
Bug in 0.4.8

### ISSUE THREAD

**Issue by CKMartens** [iobroker-community-adapters/ioBroker.discovergy#51]
See iobroker Forum [#161](https://forum.iobroker.net/topic/17240/aufruf-neuer-adaper-discovergy/161)

**Comment by DutchmanNL** [comment]
please try again from GitHub

<img width="1007" alt="Schermafbeelding 2019-10-14 om 14 44 47" src="https://user-images.githubusercontent.com/7318445/66752205-2e8a6080-ee91-11e9-949c-e126335cba16.png">
