### ISSUE TITLE
(1094) Information received from Discovergy which is not yet part of this adapter

### ISSUE THREAD

**Issue by chlamke** [iobroker-community-adapters/ioBroker.discovergy#55]
using Awattar with Discovergy Meter, I receive constant error messages like this:

discovergy.0 | 2019-12-01 19:28:46.034 | error | (1094) Send this information to developer : loadProfileType : SLP
discovergy.0 | 2019-12-01 19:28:46.034 | error | (1094) Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2019-12-01 19:28:46.033 | error | (1094) Send this information to developer : fullSerialNumber : 1ESY116xxxxxxx

**Comment by DutchmanNL** [comment]
ist bereits in version 0.4.4 gelöst, diese befindet sich noch nicht in stable wird aber bald released.
Als beta ueber repository latest berets verfuegbar.

**Comment by DutchmanNL** [comment]
duplicates https://github.com/iobroker-community-adapters/ioBroker.discovergy/issues/44

**Comment by HabibA007** [comment]
immer noch nicht released?
Zumindest ist der Fehler bei einer heutigen Installation immer noch da.... aktuell ist 0.4.0
