### ISSUE TITLE
ESY Stromzähler Information received wich is not part of this adapter

### ISSUE THREAD

**Issue by haarchri** [iobroker-community-adapters/ioBroker.discovergy#60]
```
discovergy.0 | 2020-01-12 14:34:34.555 | error | (32383) Send this information to developer : loadProfileType : SLP
-- | -- | -- | --
discovergy.0 | 2020-01-12 14:34:34.555 | error | (32383) Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2020-01-12 14:34:34.554 | error | (32383) Send this information to developer : fullSerialNumber : xxx
discovergy.0 | 2020-01-12 14:34:34.554 | error | (32383) Information received from Discovergy which is not yet part of this adapter
discovergy.0 | 2020-01-12 14:34:34.554 | error | (32383) Send this information to developer : manufacturerId : ESY
discovergy.0 | 2020-01-12 14:34:34.553 | error | (32383) Information received from Discovergy which is not yet part of this adapter
```

**Comment by haarchri** [comment]
i can also add full serialnumber if needed

**Comment by HabibA007** [comment]
I've the same issue...

**Comment by DutchmanNL** [comment]
which adapter version ?

**Comment by HabibA007** [comment]
The official 0.4.0

**Comment by DutchmanNL** [comment]
Please try 0.5.0

**Comment by HabibA007** [comment]
I don't know why, but I only get v0.4.9 not 0.5.0 which I see in WebGUI.

`pi@iobroker:/opt/iobroker/node_modules $ npm view iobroker.discovergy

iobroker.discovergy@0.4.9 | MIT | deps: 2 | versions: 12
Receive all data of Discovery API into ioBroker to have your daily, weekly etc power consumption and delivery monitored
https://github.com/iobroker-community-adapters/ioBroker.discovergy

keywords: energy, meter, consumption, messurement

dist
.tarball: https://registry.npmjs.org/iobroker.discovergy/-/iobroker.discovergy-0.4.9.tgz
.shasum: 2d37498985c1dec8761219874174cb021d049364
.integrity: sha512-yvoK2Y+2gbow4xWnO4cnvoQC9WQqN/iOKwfJH/5YsOz4kQ6+Nud9q+aXDCT2AwyCX8CVaDOhQmfd7x4bxjzsTA==
.unpackedSize: 115.8 kB

dependencies:
@iobroker/adapter-core: ^1.0.3 request: ^2.88.0

maintainers:
- buzzy1337 <buzzy1337@outlook.de>
- forelleblau <marceladam@gmx.ch>
- garfonso <garfonso@mobo.info>
- algar42 <igor.aleschenkov@gmail.com>
- ctjaeger <info@ct-j.de>
- zefau <zefau@mailbox.org>
- basgo <basgo@gmx.net>
- alcalzone <d.griesel@gmx.net>
- nisiode <nisio.air@gmail.com>
- bluefox <dogafox@gmail.com>
- prinzeisenherz1 <Schneider.JNL@googlemail.com>
- foxthefox <foxthefox@wysiwis.net>
- meistertr <meistertr.smarthome@gmail.com>
- ldittmar <iobroker@lmdsoft.de>
- jey-cee <jey-cee@live.com>
- apollon77 <github@fischer-ka.de>
- andiling <andreas.lingstaedt@googlemail.com>
- dutchmannl <rdrozda@hotmail.com>
- jogibear9988 <jochen.kuehner@gmx.de>

dist-tags:
latest: 0.4.9

published 4 months ago by dutchmannl <rdrozda@hotmail.com>`

But the 0.4.9 seems to work fine :-) thx

**Comment by HabibA007** [comment]
`

discovergy.0 | 2020-02-15 18:50:26.306 | info | (3391) Discovergy meter found at your account with serial : 61230000
-- | -- | -- | --
discovergy.0 | 2020-02-15 18:50:25.704 | info | (3391) Discovergy Adapter startet, trying to discover meters associated with your account
discovergy.0 | 2020-02-15 18:50:25.575 | info | (3391) starting. Version 0.4.9 in /opt/iobroker/node_modules/iobroker.discovergy, node: v10.19.0
host.iobroker | 2020-02-15 18:50:18.308 | info | instance system.adapter.discovergy.0 started with pid 3391

`

**Comment by DutchmanNL** [comment]
0.5.0 will be installabel tomorrow or using latest repo

**Comment by haarchri** [comment]
yes with 0.4.9 it works now - red message gone away ;)
thanks

**Comment by DutchmanNL** [comment]
> yes with 0.4.9 it works now - red message gone away ;)
> thanks

i assume you mean 0.5 :), great thank you providing feedback !
