### ISSUE TITLE
Information received from Discovergy which is not yet part of this adapter

### ISSUE THREAD

**Issue by AF-112** [iobroker-community-adapters/ioBroker.discovergy#73]
Hallo Dutchman,

anscheinend kommen bei mir Infos von Discovergy zurück womit dein Adapter in Version 0.5.0 nichts anfangen kann.

Genau sind das:
- fullSerialNumber :
- manufacturerID : ESY
- loadProfileType : SLP

**Comment by DutchmanNL** [comment]
Hi @AF-112 

kannst du mir mal bitte die komplette Fehlermeldung schicken diese Elementen sind eigentlich schon ne zeit lang drin ?!

https://github.com/iobroker-community-adapters/ioBroker.discovergy/blob/master/lib/state_attr.js#L135-L144

https://github.com/iobroker-community-adapters/ioBroker.discovergy/blob/master/lib/state_attr.js#L110-L114

**Comment by DutchmanNL** [comment]
@AF-112 ?

**Comment by AF-112** [comment]
Servus,
mir ist zwischenzeitlich leider mein ioBroker komplett abgeschmiert und das Backup lässt sich nicht richtig wiederherstellen. Muss die Kiste erst neu aufsetzen, was ein wenig Arbeit und Zeit bedarf. Die aktuellste Version des Adapters hatte ich jedoch. Wenn das Problem nach dem neu aufsetzen weiterhin besteht schick ich die Infos durch.

**Comment by DutchmanNL** [comment]
Oh tut mir leid das zu hören das kan nerven 

Melde dich bitte ob es wohl oder nicht klappt in das issue zu schließen Oder weitere Analyse;)

**Comment by DutchmanNL** [comment]
cannot reproduce
