### ISSUE TITLE
Wrong Unit

### ISSUE THREAD

**Issue by skvarel** [iobroker-community-adapters/ioBroker.discovergy#79]
Wrong unit of consumption

![grafik](https://user-images.githubusercontent.com/1114419/79692737-14c63d80-8267-11ea-8a8e-c87f42552f51.png)

**Comment by DutchmanNL** [comment]
solved 0.5.4 https://github.com/iobroker-community-adapters/ioBroker.discovergy/commit/ae439861b1c8691ab0cc921837843b78b56cf027
